CREATE TABLE `page_remain` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`uuid` VARCHAR(60) NULL DEFAULT NULL,
	`createDate` DATETIME NULL DEFAULT NULL,
	`modifyDate` DATETIME NULL DEFAULT NULL,
	`mark` VARCHAR(230) NULL DEFAULT NULL,
	`status` INT(1) NULL DEFAULT NULL,
	`isActive` INT(1) NULL DEFAULT NULL,
	`accessUri` VARCHAR(250) NULL DEFAULT NULL,
	`plateform` VARCHAR(100) NULL DEFAULT NULL,
	`referType` INT(11) NULL DEFAULT NULL,
	`referId` INT(11) NULL DEFAULT NULL,
	`ip` VARCHAR(150) NULL DEFAULT NULL,
	`openId` VARCHAR(70) NULL DEFAULT NULL,
	`unionid` VARCHAR(70) NULL DEFAULT NULL,
	`userId` INT(11) NULL DEFAULT NULL,
	`firstView` DATETIME NULL DEFAULT NULL,
	`lastView` DATETIME NULL DEFAULT NULL,
	`remainTime` INT(11) NULL DEFAULT NULL COMMENT '单位秒',
	PRIMARY KEY (`id`)
)
COMMENT='页面停留统计'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
